### ISSUE TITLE
vendor-bundle-xxx.js `rev` not changed when app-bundle-xxx.js `rev` changed.

### ISSUE THREAD

**Issue by xiwc** [aurelia/cli#465]
**I'm submitting a bug report**

* **Library Version:**
0.24.0

**Please tell us about your environment:**
* **Operating System:**
Linux 

* **Node Version:**
4.4.x

* **NPM Version:**
3.10.x

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**
i have three bundle:
app-bundle-xxx.js
deps-bundle-xxx.js
vendor-bundle-xxx.js

vendor-bundle-xxx.js `rev` not changed when app-bundle-xxx.js `rev` changed.
but app-bundle-xxx.js is loading by vendor-bundle-xxx.js.

so browser can not load changed app-bundle-xxx.js as vendor-bundle-xxx.js  was cached in index.html.

**Expected/desired behavior:**

vendor-bundle-xxx.js `rev` changed too when app-bundle-xxx.js `rev` changed.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by edwardridge** [comment]
This happens for me as well, but only on --watch: if I run a full au build it updates the vendor bundle correctly.

**Comment by sbolel** [comment]
I think this is related to issues https://github.com/aurelia/cli/issues/472, https://github.com/aurelia/cli/issues/378, and PR https://github.com/aurelia/cli/pull/427. I think it should be resolved with the next release. 

@edwardridge what's the motivation for using `rev` in an environment that use with `au run`? It should only be necessary when building minified bundles to release to production.

---

Because of this though, my team decided to put everything into a single bundle and then generate a hash manually in the `aurelia_project` build task. We don't use the `rev` option for any environment in `aurelia.json` since that's handled by our manual task. We also changed `configTarget` in `aurelia.json` to a filename that doesn't exist because that somehow prevents the order of `define` statements from changing. Bundling things into separate files has no advantage over bundling into a single file -- if anything, the browser has to make more requests and spends more time to run the same code.

**Comment by AStoker** [comment]
This still appears to be happening. In particular for us, we have multiple bundles, and it's our `settings-bundle` that is changing, and the `vendor-bundle` that continues to have the same revision hash.  
I think the issue is that the hashing of the file contents of the `vendor-bundle` is happening _before_ we add the require config (which would contain the different hashed reference for my `settings-bundle`). So the vendor bundle's hash doesn't change because it's contents haven't changed, but the require config that's added later _has_ changed.  
I'm gonna dig into it a bit...

**Comment by xiwc** [comment]
i hash bundle again using gulp task.

**Comment by sbolel** [comment]
@AStoker the config does change, thats exactly it. It's the order of the dependencies that changes, and I think it's the last line in the bundle. You can try sorting them in the build taks and rewriting that line. 

We build, use Closure compiler, then generate a hash for the result manually. Works well. 

@xiwc does the hash stay the same if you build twice without changing src?

**Comment by AStoker** [comment]
@sbolel, I was honestly just thinking about swapping the order of the hash generating :P 
If you look at [this](https://github.com/aurelia/cli/blob/master/lib/build/bundle.js#L182) line of code, this is where we generate the actual hash based off the concatenated file contents. It's not until a few lines down that we actually append the loader config to the bundle (after the hashing).  

If we were to simply move the hash generation to execute _after_ we add the loader configuration, that would ensure that any changes to other file bundle names would cause the vendor bundle to appropriately have a different hash. 

I'm going to make a PR, and perhaps you can see if that solves your issue.
@xiwc, seems like we should require you to generate _another_ hashed bundle after building, I'd like to make that process of yours simpler :)

**Comment by sbolel** [comment]
@AStroker I'm going to try out your PR today, thank you!

**Comment by xiweicheng** [comment]
@AStoker I will test when your PR merged and released.

Now, my way in prod:

![image](https://cloud.githubusercontent.com/assets/9198971/23049478/615bed12-f4f7-11e6-93bf-52f77bd144a9.png)
![image](https://cloud.githubusercontent.com/assets/9198971/23049491/6d8c780e-f4f7-11e6-8615-74d71c9c1e45.png)
![image](https://cloud.githubusercontent.com/assets/9198971/23049500/73e94254-f4f7-11e6-9c09-48c1bcaa05a9.png)

Hope helps someone!
