### ISSUE TITLE
Bundles with no source files fail to build on changes

### ISSUE THREAD

**Issue by flekschas** [aurelia/cli#549]
**I'm submitting a bug report**

**CLI Version:**
0.26.1

**Operating System:**
OSX 10.11.6

**Node Version:**
6.9.5

**NPM Version:**
4.1.2

**Browser:**
all

**Language:**
ESNext

**Current behavior:**
I have bundle definition for simple concatenation of two or more JS files, which looks like this:

```
{
  "name": "tsne-worker.js",
  "prepend": [
    "node_modules/tsne-js/build/tsne.min.js",
    "src/utils/worker-tsne.js"
  ],
  "source": []
}
```

Since I only want to concat files for a JS worker, I have an empty array of source files. The initial build works fine on startup (`au run --watch`) but fails when I edit one of the build files listed in _prepend_ with the following error message:

```
gulp-notify: [Error running Gulp] Error: Cannot set property 'requiresBuild' of null
```

Afterwards Gulp seems to have gotten stuck and stops building anything, which can be resolved by a simple restart of `au`.

**Expected/desired behavior:**
Since the initial start up build works fine I would assume that subsequent builds, triggered by file changes, work too.

**What is the motivation / use case for changing the behavior?**
The bundles I want to create are for JS workers, which requires simple concatenation of some library files and a worker definition.

**Comment by JeroenVinke** [comment]
Thanks for creating the issue. I can't seem to reproduce this issue, could you share the exact steps I need to take in order to get this error?

**Comment by flekschas** [comment]
This bug seems to have been fixed in `v0.27.0`. I can't reproduce it anymore.

Thanks for checking and sorry for the waste of time.

**Comment by delebash** [comment]
Windows 10x64
node 8.4.0
aurelia-cli 0.31.1
javascript
webstorm

For me I think the problem stems from the sourcemap path in windows and how aurelia handles that path on windows

In order for webstorm to hit breakpoints I had to change the `sourceRoot: 'src'` in sourcemaps  transpile.js to ` sourceRoot: '../src'`
after this debugging works but as @flekschas I get the same error when changing code using watch.

To reproduce 
1. Create a new aurelia-cli project
2. Open the project in webstorm
3.Create a new javascript debug setting
4. Run and debug the project by running au run --watch and then start webstorms debugger
5. Breakpoints will not be hit.
6. Change sourcemaps directory to ` sourceRoot: '../src'`

Breakpoints will now be hit but you get the same problem as op.

Note:  This is not a problem with webstorm as the es6 skeleton-navigation-app works fine after changing the sourcemaps directory.

**Comment by JesseNewman19** [comment]
I am still having this issue with the latest version of the CLI.
