### ISSUE TITLE
Jest test suite fails to run

### ISSUE THREAD

**Issue by jholland918** [aurelia/cli#822]
**I'm submitting a bug report**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.4

* **NPM Version:**
5.5.1

* **Browser:**
Chrome 64.0.3282.140 (Official Build) (64-bit)

* **Language:**
all

* **Loader/bundler:**
Webpack

**Current behavior:**
Running `au jest` fails to run the pre-configured test and prints this output
```
...\au-webpack-babel-jest> au jest
 FAIL  test\unit\app.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'Node' of undefined

      at patchNotifyChange (node_modules/aurelia-pal-nodejs/dist/nodejs-pal-builder.js:55:35)
      at Object.<anonymous> (test/jest-pretest.js:6:33)

Test Suites: 1 failed, 1 total
```

* **What is the expected behavior?**
Steps to reproduce

Run `au new`

```
Project Configuration
    Name: au-webpack-babel-jest
    Platform: Web
    Bundler: Webpack
    Loader: None
    Transpiler: Babel
    Markup Processor: None
    CSS Processor: None
    Unit Test Runner: Jest
    Integration Test Runner: None
    Editor: Visual Studio Code
```

_Would you like to create this project?_
[Yes]

_Would you like to install the project dependencies?_
[Yes]

Run `au jest`

* **What is the motivation / use case for changing the behavior?**
So newly created projects using Jest work out of the box.

**Comment by Alexander-Taran** [comment]
It's been fixed in 
"aurelia-pal-nodejs": "1.0.0-beta.3.0.0",
you got to update the dependency manually for now.
I cant find the issue at the moment but I stumbled upon the same behavior and found it somewhere around here.
So there you have it (-:

**Comment by jholland918** [comment]
Updating aurelia-pal-nodejs to 1.0.0-beta.3.0.0 worked, thanks for the help!

I still see we have version 1.0.0-beta.2.0.0 in /lib/dependencies.json. I wonder if there's a reason for not bumping the version or if it's just an oversight.

**Comment by BBosman** [comment]
I'm seeing this issue again, but on `aurelia-pal-nodejs@1.0.0-beta.3.1.0`.

**Comment by Alexander-Taran** [comment]
That'd make me responsible
Only thing changed between 3.0.0 and 3.1.0 was addition of NodeList

https://github.com/aurelia/pal-nodejs/compare/394da3e21b55925e16c3bb91294a245acfa99bc2...master

**Comment by BBosman** [comment]
Yes, same repro.

Thanks for looking into it!

**Comment by Alexander-Taran** [comment]
seems like you created project anew and did not update pal-nodejs
au new..
your steps..
updated pal-nodejs and everything worked.

note: cli was not released with the updates

also, probably need another bump of pal-nodejs dependency in produced configs.

**Comment by BBosman** [comment]
That does solve it in my test repo, but not in my actual (private) repo. So now I need to figure out what's different between those two.

**Comment by JeroenVinke** [comment]
Try to remove the package-lock.json before installing the update

**Comment by Alexander-Taran** [comment]
yeah.. and get rid of npm as well (-:
yarn add ftw..

**Comment by Alexander-Taran** [comment]
@vermilion what's your use case not covered by yarn?

**Comment by martynchamberlin** [comment]
This issue was originally created because of [this JSDOM change](https://github.com/jsdom/jsdom/pull/2098) per what **domenic** [said](https://github.com/jsdom/jsdom/pull/2092#discussion_r162832406): 

> We no longer store _core on Window after #2098. 

You can see `_core` being referenced in `aurelia-pal-nodejs` [here](https://github.com/aurelia/pal-nodejs/blob/4044b30f7da4bb0f935717e1095a0ba0a918f851/src/nodejs-pal-builder.ts#L67) still, however. So it looks like the [fix](https://github.com/aurelia/pal-nodejs/issues/24#issuecomment-360018804) was to ensure that the JSDOM dependency doesn't progress past `11.5.1`. 

The problem is that in my project, I was trying to utilize `aurelia-pal-nodejs`  but I was also specifying the latest version of JSDOM for use elsewhere, and that latest version was the instance that got used in the `aurelia-pal-nodejs` dependency, and thereby caused the error in this issue (#822) to resurface. 

Hopefully this fix is temporary and the plan is to update the version of `jsdom` in `aurelia-pal-nodejs` to the latest version and no longer reference `_core`?

**Comment by JeroenVinke** [comment]
@martynchamberlin thanks for looking into this. Please open an issue in the aurelia-pal-nodejs repo so it can be looked into
